import portraitData from '../portraits.json';

// Data-shape guard for the 24x29 cast portrait sheet (generated by
// scripts/generate-portraits.mjs). Portraits aren't wired into a screen yet;
// this locks the atlas contract a future loader will rely on.
const sheet = portraitData as {
  cell: { w: number; h: number };
  palette: Record<string, string | null>;
  sprites: Record<string, string[]>;
};

const IDS = [
  'r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10',
  'u0', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10',
];
const EXPRESSIONS = ['rest', 'joy', 'ko'] as const;

describe('portraits.json', () => {
  it('is a 24x29 sheet', () => {
    expect(sheet.cell).toEqual({ w: 24, h: 29 });
  });

  it('has every cast member in all three expressions (66 portraits)', () => {
    const expected = IDS.flatMap((id) => EXPRESSIONS.map((e) => `${id}:${e}`));
    expect(expected).toHaveLength(66);
    for (const key of expected) expect(sheet.sprites).toHaveProperty(key);
    expect(Object.keys(sheet.sprites)).toHaveLength(66);
  });

  it('every portrait is exactly 24 wide x 29 tall', () => {
    for (const [key, rows] of Object.entries(sheet.sprites)) {
      expect(rows).toHaveLength(sheet.cell.h);
      for (const row of rows) expect(row).toHaveLength(sheet.cell.w);
    }
  });

  it('every character used exists in the palette', () => {
    for (const rows of Object.values(sheet.sprites)) {
      for (const row of rows) {
        for (const ch of row) expect(ch in sheet.palette).toBe(true);
      }
    }
  });

  it('palette stays within the 24-color budget', () => {
    expect(Object.keys(sheet.palette).length).toBeLessThanOrEqual(24);
  });

  it('gives each player three distinct expressions (rest / joy / ko)', () => {
    for (const id of IDS) {
      const [rest, joy, ko] = EXPRESSIONS.map((e) => JSON.stringify(sheet.sprites[`${id}:${e}`]));
      expect(rest).not.toEqual(joy);
      expect(rest).not.toEqual(ko);
      expect(joy).not.toEqual(ko);
    }
  });

  it('Dario Flint (r9) keeps his fire-orange hair in every expression', () => {
    const fireChar = Object.entries(sheet.palette).find(([, hex]) => hex === '#ff6a00')?.[0];
    expect(fireChar).toBeDefined();
    for (const e of EXPRESSIONS) {
      expect(sheet.sprites[`r9:${e}`].some((row) => row.includes(fireChar as string))).toBe(true);
    }
  });
});
