import tables from './formation-tables.json';
import { clamp, dist, GOAL_CENTER_X, PITCH_W, PITCH_H, type Vec } from './geometry';

// Positional-table movement (m0.5 rework, SWOS-style 35-area tactics table —
// spec: docs/superpowers/specs/2026-07-18-positional-movement.md). The table
// supplies positional INTENT for the 10 outfield slots; active decisions
// (carrier/presser/receiver/chaser) stay in engine.ts. formation-tables.json
// is GENERATED by scripts/gen-formation-tables.mjs — never hand-edit it;
// corrections go in scripts/formation-overrides.json.

export const GRID_COLS: number = tables.grid.cols;
export const GRID_ROWS: number = tables.grid.rows;
export const CELL_W: number = PITCH_W / GRID_COLS;
export const CELL_H: number = PITCH_H / GRID_ROWS;

/** Turnover blend length: targets lerp old-phase → new-phase over this many ticks. */
export const BLEND_TICKS = 10;

// GK angle-narrowing (m0.6, T7 — the follow-up the m0.5 movement spec deferred):
// the keeper stands ON the segment from his own goal center to the ball, at a
// depth off the goal line that GROWS as the ball approaches, narrowing the
// shooting angle. Replaces the m0.4 anchor-pull relic (anchor [0.5, 0.94],
// 0.15x/0.10y uniform ball pull). Pure arithmetic — zero rng draws.
//
// Penalty-box proportions restated from the real senior pitch (105m x 68m),
// mirroring src/render/Pitch.tsx's PENALTY_BOX_W/D ratios — sim must never
// import from render, so the named constants are hardcoded here.
const GK_BOX_HALF_W = Math.round(PITCH_W * (40.3 / 68) / 2); // 2015 cm
const GK_BOX_DEPTH = Math.round(PITCH_H * (16.5 / 105));     // 1650 cm
// Depth ramp: MAX at the goal, shedding SLOPE cm of depth per cm of ball
// distance, floored at MIN (reached beyond (MAX-MIN)/SLOPE = 4000 cm).
// Tuned against the balance rails (200 seeds, ROVERS vs UNITED, commit-time
// measurement): m0.5 baseline goals/match 2.670, shots/match 8.860, saveRate
// 0.6985, blowout strongGoals/match 7.415 — at these constants: goals/match
// 2.720, shots/match 9.075, saveRate 0.6913, blowout 7.480. All rails green.
const GK_DEPTH_MAX = 1000;  // cm off the line with the ball at the goal (upper clamp)
const GK_DEPTH_MIN = 200;   // cm off the line with play far away (lower clamp)
const GK_DEPTH_SLOPE = 0.2; // cm of depth shed per cm of ball distance

export function gkTarget(team: 0 | 1, ball: Vec): Vec {
  const b = ballForTeam(team, ball);
  const goal: Vec = { x: GOAL_CENTER_X, y: PITCH_H }; // own goal, team-0 frame
  const d = dist(goal, b);
  // Off-line depth grows as the ball approaches; never placed beyond the ball.
  const depth = Math.min(clamp(GK_DEPTH_MAX - GK_DEPTH_SLOPE * d, GK_DEPTH_MIN, GK_DEPTH_MAX), d);
  const t = d === 0 ? 0 : depth / d;
  // Box clamps are safety rails (a shot-flight ball can sit behind the goal
  // line; future retunes may raise GK_DEPTH_MAX past the box bounds): never
  // wider than the penalty box, never deeper than it, never behind the line.
  const x = clamp(Math.round(goal.x + (b.x - goal.x) * t), GOAL_CENTER_X - GK_BOX_HALF_W, GOAL_CENTER_X + GK_BOX_HALF_W);
  const y = clamp(Math.round(goal.y + (b.y - goal.y) * t), PITCH_H - GK_BOX_DEPTH, PITCH_H);
  return team === 0 ? { x, y } : { x: PITCH_W - x, y: PITCH_H - y };
}

/**
 * Team 1 mirrors the ball into team-0 frame before sampling. Algebraically
 * (PITCH_W - b)/cellW - 0.5 == (cols-1) - (b/cellW - 0.5) over the reals, but
 * NOT bit-identical to mirroring the continuous coordinates in IEEE doubles
 * (1-ulp grid-coord differences; 1 cm target differences at ~0.08% of probes
 * on exact .5 rounding ties). This integer-mirror formulation IS the canonical
 * convention (spec disposition record, m0.5 review): it is the only one under
 * which the 180°-rotation property test holds exactly by construction.
 */
function ballForTeam(team: 0 | 1, ball: Vec): Vec {
  return team === 0 ? ball : { x: PITCH_W - ball.x, y: PITCH_H - ball.y };
}

/**
 * Cell-center-convention bilinear sample of one phase table for one outfield
 * slot (0..9), ball in the sampling team's frame. Returns unrounded
 * normalized fractions (team-0 frame) — callers blend, then round once.
 */
function samplePhase(phase: number[][][], slot: number, ball: Vec): { x: number; y: number } {
  const gx = clamp(ball.x / CELL_W - 0.5, 0, GRID_COLS - 1);
  const gy = clamp(ball.y / CELL_H - 0.5, 0, GRID_ROWS - 1);
  const x0 = Math.floor(gx);
  const y0 = Math.floor(gy);
  const x1 = Math.min(x0 + 1, GRID_COLS - 1);
  const y1 = Math.min(y0 + 1, GRID_ROWS - 1);
  const fx = gx - x0;
  const fy = gy - y0;
  const s = phase[slot];
  const c00 = s[y0 * GRID_COLS + x0];
  const c10 = s[y0 * GRID_COLS + x1];
  const c01 = s[y1 * GRID_COLS + x0];
  const c11 = s[y1 * GRID_COLS + x1];
  const topX = c00[0] + (c10[0] - c00[0]) * fx;
  const topY = c00[1] + (c10[1] - c00[1]) * fx;
  const botX = c01[0] + (c11[0] - c01[0]) * fx;
  const botY = c01[1] + (c11[1] - c01[1]) * fx;
  return { x: topX + (botX - topX) * fy, y: topY + (botY - topY) * fy };
}

function phaseTable(inPossession: boolean): number[][][] {
  return inPossession ? tables.phases.inPossession : tables.phases.outOfPossession;
}

/**
 * Table target for engine slot 1..10 (GK slot 0 is gkTarget's job), blending
 * fromInPossession → toInPossession by t (0..1; equal phases or t >= 1 skip
 * the second sample). Sampled in the team's mirrored frame, rounded once to
 * integer cm, then rotated 180° for team 1 (tactical-relative slot semantics).
 */
export function blendedTableTarget(
  team: 0 | 1, engineSlot: number, fromInPossession: boolean, toInPossession: boolean, t: number, ball: Vec,
): Vec {
  const b = ballForTeam(team, ball);
  const slot = engineSlot - 1;
  const to = samplePhase(phaseTable(toInPossession), slot, b);
  let nx = to.x;
  let ny = to.y;
  if (fromInPossession !== toInPossession && t < 1) {
    const from = samplePhase(phaseTable(fromInPossession), slot, b);
    nx = from.x + (to.x - from.x) * t;
    ny = from.y + (to.y - from.y) * t;
  }
  const x = Math.round(nx * PITCH_W);
  const y = Math.round(ny * PITCH_H);
  return team === 0 ? { x, y } : { x: PITCH_W - x, y: PITCH_H - y };
}

/** Settled (no-blend) table target — the common case and the test surface. */
export function tableTarget(team: 0 | 1, engineSlot: number, inPossession: boolean, ball: Vec): Vec {
  return blendedTableTarget(team, engineSlot, inPossession, inPossession, 1, ball);
}

// Frozen GK kickoff spot (team-0 frame, integer cm): the retired m0.4 anchor
// rule sampled at the center spot — round(9870 + (5250 - 9870) * 0.10) = 9408.
// Kept verbatim through the m0.6 angle-narrowing change (it sits inside the
// new box clamps) so restarts stay placed exactly as before.
const GK_KICKOFF_X = 3400;
const GK_KICKOFF_Y = 9408;

/** Dedicated kickoff spot per engine slot (0 = GK via the frozen kickoff spot). */
export function kickoffPos(team: 0 | 1, engineSlot: number): Vec {
  if (engineSlot === 0) {
    return team === 0
      ? { x: GK_KICKOFF_X, y: GK_KICKOFF_Y }
      : { x: PITCH_W - GK_KICKOFF_X, y: PITCH_H - GK_KICKOFF_Y };
  }
  const cell = tables.kickoff[engineSlot - 1];
  const x = Math.round(cell[0] * PITCH_W);
  const y = Math.round(cell[1] * PITCH_H);
  return team === 0 ? { x, y } : { x: PITCH_W - x, y: PITCH_H - y };
}
