import tables from './formation-tables.json';
import { clamp, PITCH_W, PITCH_H, type Vec } from './geometry';

// Positional-table movement (m0.5 rework, SWOS-style 35-area tactics table —
// spec: docs/superpowers/specs/2026-07-18-positional-movement.md). The table
// supplies positional INTENT for the 10 outfield slots; active decisions
// (carrier/presser/receiver/chaser) stay in engine.ts. formation-tables.json
// is GENERATED by scripts/gen-formation-tables.mjs — never hand-edit it;
// corrections go in scripts/formation-overrides.json.

export const GRID_COLS: number = tables.grid.cols;
export const GRID_ROWS: number = tables.grid.rows;
export const CELL_W: number = PITCH_W / GRID_COLS;
export const CELL_H: number = PITCH_H / GRID_ROWS;

/** Turnover blend length: targets lerp old-phase → new-phase over this many ticks. */
export const BLEND_TICKS = 10;

// GK is deliberately NOT in the tables this milestone (angle-narrowing is a
// separate follow-up commit): this preserves the m0.4 anchor behavior exactly —
// fixed anchor [0.50, 0.94] with the retired uniform ball pull (0.15x / 0.10y).
const GK_ANCHOR_X = 0.50;
const GK_ANCHOR_Y = 0.94;
const GK_PULL_X = 0.15;
const GK_PULL_Y = 0.10;

export function gkTarget(team: 0 | 1, ball: Vec): Vec {
  const baseX = GK_ANCHOR_X * PITCH_W;
  const baseY = (team === 0 ? GK_ANCHOR_Y : 1 - GK_ANCHOR_Y) * PITCH_H;
  const x = clamp(Math.round(baseX + (ball.x - baseX) * GK_PULL_X), 0, PITCH_W);
  const y = clamp(Math.round(baseY + (ball.y - baseY) * GK_PULL_Y), 0, PITCH_H);
  return { x, y };
}

/**
 * Team 1 mirrors the continuous grid coordinates before sampling (spec).
 * Mirroring the integer ball position first computes the same quantity
 * exactly — (PITCH_W - b)/cellW - 0.5 == (cols-1) - (b/cellW - 0.5) — while
 * keeping the mirror an exact integer operation.
 */
function ballForTeam(team: 0 | 1, ball: Vec): Vec {
  return team === 0 ? ball : { x: PITCH_W - ball.x, y: PITCH_H - ball.y };
}

/**
 * Cell-center-convention bilinear sample of one phase table for one outfield
 * slot (0..9), ball in the sampling team's frame. Returns unrounded
 * normalized fractions (team-0 frame) — callers blend, then round once.
 */
function samplePhase(phase: number[][][], slot: number, ball: Vec): { x: number; y: number } {
  const gx = clamp(ball.x / CELL_W - 0.5, 0, GRID_COLS - 1);
  const gy = clamp(ball.y / CELL_H - 0.5, 0, GRID_ROWS - 1);
  const x0 = Math.floor(gx);
  const y0 = Math.floor(gy);
  const x1 = Math.min(x0 + 1, GRID_COLS - 1);
  const y1 = Math.min(y0 + 1, GRID_ROWS - 1);
  const fx = gx - x0;
  const fy = gy - y0;
  const s = phase[slot];
  const c00 = s[y0 * GRID_COLS + x0];
  const c10 = s[y0 * GRID_COLS + x1];
  const c01 = s[y1 * GRID_COLS + x0];
  const c11 = s[y1 * GRID_COLS + x1];
  const topX = c00[0] + (c10[0] - c00[0]) * fx;
  const topY = c00[1] + (c10[1] - c00[1]) * fx;
  const botX = c01[0] + (c11[0] - c01[0]) * fx;
  const botY = c01[1] + (c11[1] - c01[1]) * fx;
  return { x: topX + (botX - topX) * fy, y: topY + (botY - topY) * fy };
}

function phaseTable(inPossession: boolean): number[][][] {
  return inPossession ? tables.phases.inPossession : tables.phases.outOfPossession;
}

/**
 * Table target for engine slot 1..10 (GK slot 0 is gkTarget's job), blending
 * fromInPossession → toInPossession by t (0..1; equal phases or t >= 1 skip
 * the second sample). Sampled in the team's mirrored frame, rounded once to
 * integer cm, then rotated 180° for team 1 (tactical-relative slot semantics).
 */
export function blendedTableTarget(
  team: 0 | 1, engineSlot: number, fromInPossession: boolean, toInPossession: boolean, t: number, ball: Vec,
): Vec {
  const b = ballForTeam(team, ball);
  const slot = engineSlot - 1;
  const to = samplePhase(phaseTable(toInPossession), slot, b);
  let nx = to.x;
  let ny = to.y;
  if (fromInPossession !== toInPossession && t < 1) {
    const from = samplePhase(phaseTable(fromInPossession), slot, b);
    nx = from.x + (to.x - from.x) * t;
    ny = from.y + (to.y - from.y) * t;
  }
  const x = Math.round(nx * PITCH_W);
  const y = Math.round(ny * PITCH_H);
  return team === 0 ? { x, y } : { x: PITCH_W - x, y: PITCH_H - y };
}

/** Settled (no-blend) table target — the common case and the test surface. */
export function tableTarget(team: 0 | 1, engineSlot: number, inPossession: boolean, ball: Vec): Vec {
  return blendedTableTarget(team, engineSlot, inPossession, inPossession, 1, ball);
}

/** Dedicated kickoff spot per engine slot (0 = GK via the preserved anchor rule). */
export function kickoffPos(team: 0 | 1, engineSlot: number): Vec {
  if (engineSlot === 0) return gkTarget(team, { x: PITCH_W / 2, y: PITCH_H / 2 });
  const cell = tables.kickoff[engineSlot - 1];
  const x = Math.round(cell[0] * PITCH_W);
  const y = Math.round(cell[1] * PITCH_H);
  return team === 0 ? { x, y } : { x: PITCH_W - x, y: PITCH_H - y };
}
